[package]
name = "doghttpclient"
version = "0.1.0"
description = "dogHttpClient - A lightweight API testing tool"
authors = ["you"]
edition = "2021"

[lib]
name = "doghttpclient_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open", "custom-protocol"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
